### ISSUE TITLE
harbor方面的需求

### ISSUE THREAD

**Issue by ztdawang** [buxiaomo/kube-ansible#8]
个人觉得应该增加一个安装选项：
       将kubeasy-offline-v1.25.4.tar.gz的镜像推送至 本地Harbor 仓库（增加一个推送脚本）

       make deploy harbor_url=harbor.xxx.com

**Comment by ztdawang** [comment]
另外，我在安装cilium时，还碰到一个问题：  健康检查失败（就成功了1次）

不过，倒也能正常使用。 但为什么会报错呢？麻烦帮忙解决一下，谢谢！

    Liveness:       http-get http://127.0.0.1:9879/healthz delay=0s timeout=5s period=30s #success=1 #failure=10
    Readiness:      http-get http://127.0.0.1:9879/healthz delay=0s timeout=5s period=30s #success=1 #failure=3
    Startup:        http-get http://127.0.0.1:9879/healthz delay=0s timeout=1s period=2s #success=1 #failure=105

Warning  Unhealthy  34s (x10 over 52s)  kubelet            Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused

**Comment by ztdawang** [comment]
明显部署其它应用，也是碰到了健康检查无法通过的问题

**Comment by buxiaomo** [comment]
> 个人觉得应该增加一个安装选项： 将kubeasy-offline-v1.25.4.tar.gz的镜像推送至 本地Harbor 仓库（增加一个推送脚本）
> 
> ```
>    make deploy harbor_url=harbor.xxx.com
> ```

`kubeasy-offline`文件中包含 `push-to-private-registry.sh`，可以帮助你将我打包的镜像推送到自己的私有仓库

eg: 
```
./push-to-private-registry.sh -h 172.16.2.11 -r infra -u admin -p admin
```

另外在部署时可以用过 `REGISTRY_URL` 参数指定私有仓库地址，格式参考 `Makefile` 中的说明

eg:
```
make deploy REGISTRY_URL=http://harbor.xxx.com
```

**Comment by buxiaomo** [comment]
> 另外，我在安装cilium时，还碰到一个问题： 健康检查失败（就成功了1次）
> 
> 不过，倒也能正常使用。 但为什么会报错呢？麻烦帮忙解决一下，谢谢！
> 
> ```
> Liveness:       http-get http://127.0.0.1:9879/healthz delay=0s timeout=5s period=30s #success=1 #failure=10
> Readiness:      http-get http://127.0.0.1:9879/healthz delay=0s timeout=5s period=30s #success=1 #failure=3
> Startup:        http-get http://127.0.0.1:9879/healthz delay=0s timeout=1s period=2s #success=1 #failure=105
> ```
> 
> Warning Unhealthy 34s (x10 over 52s) kubelet Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused


网络插件部署脚本均为官方文件，只对本项目做了镜像地址适配，你可以通过增加健康检查的时间防止时间太短而导致健康检查失败

**Comment by ztdawang** [comment]
好的，感谢！

**Comment by buxiaomo** [comment]
如果频繁出现，需要你检查一下cilium对环境的要求，具体可到cilium官网查阅


https://docs.cilium.io/en/stable/operations/system_requirements/
